fix(harbor): accommodate harbor 0.1.33 (#840)
harbor made breaking changes in 0.1.33
> ImportError: cannot import name 'RegistryClient' from
'harbor.registry.client'

https://github.com/laude-institute/harbor/pull/388